version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    volumes: 
      - ./v2ray.json:/etc/v2ray/config.json
      - ./log/v2ray:/var/log/v2ray
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose: 
      - 10000 //与v2ray提供的端口一致
  caddy:
    image: caddy
    container_name: caddy
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./log/caddy:/etc/caddy
      - ./caddy/data:/data
      - ./caddy/config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - "443:443"
      - "80:80"
